run_id:
continue_training:
prefix_name:
clip_pretrain:
resume: 
early_stop:
input_size: 224
word_len: 22
seed: 2024
epochs: 60
base_lr: 0.0001
weight_decay: 0.
lr_decay: 0.1
output_dir: exp
train_batch: 32
train_worker: 16
valid_batch: 32
valid_worker: 16
print_freq: 100
early_stop: 30