run_id:
continue_training:
prefix_name:
clip_pretrain:
resume: 
early_stop:
input_size: 224
word_len: 22
seed: 0
epochs: 100
base_lr: 0.0001
weight_decay: 0.
output_dir: exp
train_batch: 16
train_worker: 16
valid_batch: 16
valid_worker: 16
print_freq: 100
early_stop: 35
step: pretrain_main