clip_pretrain:
resume: 
input_size: 224
word_len: 77
seed: 23782376
milestones: 35
epochs: 100
base_lr: 0.0001
weight_decay: 0.
lr_decay: 0.1
output_dir: exp
train_batch: 32
train_worker: 16
valid_worker: 32
valid_worker: 16